### PR TITLE
Eigen arrival

### LINKED ISSUE #35: arrival run can generate not only *.arr but also *.ray (for associated eigenrays)
I would like to request the following enhancement: an arrival run can generate not only the *.arr file but also the *.ray file (for the associated eigenrays).

For some context, I'll describe how this enhancement would be useful for us. 

We have integrated a model of the surface bubble layer (SBL) into our propagation modeling. The SBL has two effects upon the propagation: 1) it modifies the sound speed profile in the surface bubble layer, causing upward refraction; 2) it causes depth-dependent attenuation in the surface bubble layer. 

In our MATLAB code, we can easily apply the SBL-related modification to the SSP BEFORE calling bellhop. On the other hand, we must apply the depth-dependent attenuation in a post-processing step i.e. AFTER calling bellhop. We do this by integrating the SBL-related attenuation over the path of the ray (using the information in the .ray file). Since we are interested in arrivals, this means that we have to do BOTH an arrival run AND an eigenray run. If we could get the *.arr and the *.ray (for the eigenrays) in a single bellhop run, that would cut our bellhop runs in half. (In our simulations, we loop over many variables, calling bellhop thousands of times. So, this enhancement would save us some time on simulations.)

### PR DESCRIPTION
**Pull request by oldstylejoe**
Add the options 'V' and 'v' to store arrival and eigenray information in the same run. 

Test - code review and check that the env files in tests/indivdual/eigen_arrival generate the same output. eigen_arrival.env runs both eigen and arrival and generates .ray and .arr. eigen.env and arrival.env run the same system, but just do eigen and arrival alone.

Closes #35

### CODE REVIEW

**Comment by kjaxon** [comment]
image
The first two worked.
image
didn't work with the eigen arrival. Did I type the wrong command?

**Comment by oldstylejoe** [comment]
Did you check the date on that executable and make sure it was built yesterday (or whenever you rebuilt the project)? Otherwise, that's very strange that it's not even recognizing the new command.

**Comment by kjaxon** [comment]
Just rebuilt
image
It worked with Nx2d but not 2d.
image
Looks like it output the right files too.

**Review by kjaxon — APPROVED** [review]
👍

**Pull request merged**
