### PR TITLE
API changes for modifying things from host program

### PR DESCRIPTION
**Pull request by lpisha**
This adds three main features:
- A memory tracking system. The host program using the `bellhopcxx` / `bellhopcuda` library, or the command line, can specify a maximum amount of memory for the instance to use. Depending on the run type, it will either compute the needed memory and fail if it can't fit, or it will resize the output arrays to exactly fit in the available memory.
- The ability to set up the library without an environment file. It uses reasonable basic defaults for all parameters; `BELLHOP(3D)` explicitly provided defaults for some parameters, so it uses those when they existed.
- Functions for the host program to call to set up each of the arrays / data structures in the input parameters with different sizes. If the array does not need to change size, the host can simply write to it, setting any associated flags for units (e.g. km / m) and a dirty flag if present for that data. If the array does need to change size, the host calls the appropriate function to reallocate the memory and then writes in the new data.

This comes with two main sets of code changes:
- Refactoring of all the code for setup, reading the environment file, allocating and deallocating memory, etc. into `module`s and `mode`s. These keep all the code to handle a specific type of parameter in a single class, and make handling all the setup steps much easier.
- API changes, both for the `extsetup` functions and that `bhcParams` is now only templated on `O3D`.

### CODE REVIEW

**Comment by lpisha** [comment]
Ready for review. Builds and appears to work on Windows though the Windows testing is minor as usual compared to the Linux testing. I also got rid of all of the warnings in the Windows build on VS 2022.

**Comment by oldstylejoe** [comment]
Thanks for the PR. I'm back in town Sunday and will look at this on Monday. Looking forward to trying out the new interface.
Sent from Yahoo Mail on Android 
 
  On Fri, Apr 7, 2023 at 12:31 AM, ***@***.***> wrote:   


@lpisha requested your review on: #19 API changes for modifying things from host program.

**Comment by oldstylejoe** [comment]
Trying to test the dll access with defaults. Is there a minimum set I have to specify? From what I read, I'd expect something like this to work:

```
#include <iostream>

#define BHC_DLL_IMPORT
#include <bhc/bhc.hpp>

void PrintLog(const char* message) {
	std::cout << message << std::flush;
}

int main() {
	bhc::bhcParams<false> params;
	bhc::bhcOutputs<false, false> outputs;
	bhc::bhcInit init;
	init.FileRoot = nullptr;
	init.outputCallback = PrintLog;
	init.prtCallback = PrintLog;

	bhc::setup(init, params, outputs);
	bhc::run(params, outputs);
	bhc::finalize(params, outputs);

	return 0;
}
```

It compiles and links fine with bellhopcxxlib.lib, but errors out with a message:

> Ocean bottom (Bdry->Bot.hs.Depth) must be at last SSP depth (ssp->z[ssp->NPts-1])Warning in ReadSzRz : Source below or too near the bottom bdry has been moved up
Warning in ReadSzRz : Receiver below or too near the bottom bdry has been moved up
setup: 0.451900 msOcean bottom (Bdry->Bot.hs.Depth) must be at last SSP depth (ssp->z[ssp->NPts-1])Preprocess: 0.132300 ms500 warning(s) thrown of the following type(s):BHC_WARN_SOURCE_OUTSIDE_BOUNDARIES: Terminating the ray trace because the source is on or outside the boundariesRun: 3.424000 msPostprocess: 0.007400 ms
d:\Users\oldst\Documents\joe\pong\dev\bellhop\testdll\x64\Release\testdll.exe (process 28232) exited with code 0.

**Comment by lpisha** [comment]
@oldstylejoe Hope this fixes the bug, please try that test program again.

**Comment by oldstylejoe** [comment]
Now it gives an out of memory error:

> setup: 0.090400 msPreprocess: 0.028100 ms500 warning(s) thrown of the following type(s):BHC_WARN_ONERAY_OUTOFMEMORY: Ran out of memory for individual ray(s), those rays have been truncatedRun: 1414.488200 msPostprocess: 0.007000 ms
d:\Users\oldst\Documents\joe\pong\dev\bellhop\testdll\x64\Release\testdll.exe (process 12016) exited with code 0.

Some sort of testing would be good. The link to that simple windows thing is below, but that's not very general. Maybe load the library in some python script for basic testing?

[https://github.com/A-New-BellHope/testdll](testdll)

**Comment by lpisha** [comment]
Just FYI, neither of the errors you have posted are errors, they are warnings. However, they do indicate that the defaults are probably not what they should be.

Unfortunately the `testdll` repo you linked is Windows-only. I will make an `examples` category in the CMake build system and copy your code into a first example.

**Comment by oldstylejoe** [comment]
Examples are great! Only thing I'd be a little worried about is how bhc::ext* functions are tested. The example code might be a good spot for that, but it could be a new task.

Yes, I probably access the ray data with something like that, and code review would be good. Since this triggers a full refactor of the interface, why don't I do that first, and I'll request you as a reviewer on that PR. I'll update the access like your example.

**Review by oldstylejoe — APPROVED** [review]

**Pull request merged**
