### PR TITLE
BELLHOP3D changes

### PR DESCRIPTION
**Pull request by lpisha**
Translation of BELLHOP3D to C++/CUDA. This enables 3D and Nx2D modes; 3D is well-tested but Nx2D is basically untested.

Using bellhopcxxlib and the headers now requires C++17, meaning UE4 compatibility is removed and UE5 is required.

Several other features are also added (2022 BELLHOP changes, separate executables mode, API improvements, more bugfixes).

### CODE REVIEW

**Comment by oldstylejoe** [comment]
Some sort of exit criteria would be really helpful. It's a massive quantity of work (85k lines!) so code review will be kind of sparse, unless you want to wait a while. I can confirm that it builds on MSVC 2022, but with more warnings than I'd normally like.

Maybe we just want to test that it compiles and some set (please specify) of the tests run?

**Comment by lpisha** [comment]
What do you mean by exit criteria? You mean criteria to accept the merge?

When I asked for your review, I was mainly looking to make sure that the changes were compatible with how you were using the system, i.e. in Unreal. In particular, I was looking for your approval for "getting rid of" the C++14/UE4 compatibility by updating main to point here.

If you're looking for some tests to run just as a basic sanity check that it's working, you could do `./run_tests.sh ray ray_tests_pass`. That should only take a minute or so.

The vast majority of the 85k lines are new 3D environment files, SSPs, etc. which were imported. The whole codebase is about 11k lines. I was not expecting a code review (though you're welcome to do that if you want).

I have had some warnings on gcc regarding unused variables and such, which are actually only unused with certain templating settings. I cleaned those up but there are more in MSVC. There are also some incorrect warnings in MSVC about conditions being constexpr and should be changed to `if constexpr`, for example `if(R3D && some_not_const_condition()) { foo(); }` would say `condition is constexpr, suggest changing to if constexpr`, which is not correct for the full condition and would require nested if statements.

**Comment by oldstylejoe** [comment]
Thanks for clarifying, and, yes, 'test criteria' probably would have been clearer. Issues might be appropriate for the compiler warnings. There're some about unreachable code after exceptions are thrown, in addition to the constexpr stuff.

**Review by oldstylejoe — APPROVED** [review]
Builds and runs in UE5 (mostly) as before. I did have to update to the templated Beam structure on the UE side, but the new template is better.

**Pull request merged**
